=== DevAkshayRaj/TrainingLabOne/Invoice.dtd
<!ELEMENT invoice (invno,invdate,customername,items,gst,net)>
<!ELEMENT invno (#PCDATA)>
<!ELEMENT invdate (#PCDATA)>
<!ELEMENT customername (#PCDATA)>
<!ELEMENT items (item+)>
<!ELEMENT item (itemno,itemname,itemprice,itemqty,units,amount)>
<!ELEMENT itemno (#PCDATA)>
<!ELEMENT itemname (#PCDATA)>
<!ELEMENT itemprice (#PCDATA)>
<!ELEMENT itemqty (#PCDATA)>
<!ELEMENT units (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT gst (#PCDATA)>
<!ELEMENT net (#PCDATA)>

=== DevAkshayRaj/TrainingLabOne/Invoice.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE invoice SYSTEM "Invoice.dtd">
<invoice>
	<invno>344</invno>
	<invdate>09/03/2021</invdate>
	<customername>Akshay Raj B</customername>
	<items>
		<item>
			<itemno>4343</itemno>
			<itemname>Rice</itemname>
			<itemprice>700</itemprice>
			<itemqty>5 Kg</itemqty>
			<units>6</units>
			<amount>3500</amount>
		</item>
		<item>
			<itemno>34343</itemno>
			<itemname>Dhal</itemname>
			<itemprice>300</itemprice>
			<itemqty>20 Kg</itemqty>
			<units>8</units>
			<amount>6000</amount>
		</item>
	</items>
	<gst>409</gst>
	<net>9500</net>
</invoice>
